---
title: ACS2022
author: Fatima Yunusa, Michelle Ji, Jiaqi Lai, Lexi Knight, and Aliza Mithwani
date: today
date-format: long
format: pdf
bibliography: references.bib

---

## Obtaining ACS 2022 Data

In order to obtain data for the 2022 American Community Survey:

-   Login to the IPUMS USA site
-   click "get data"
-   go to "select sample"
-   Un- select "default sample from each year"
-   Select "2022 ACS"
-   Then "submit sample selections"
-   Select "household" then "geographic" then select 'Stateicp'
-   Select "person" then "education" then select 'educ'
-   After selecting the desired variables, click "View cart" and then click "create data extract".
-   Once satisfied with the dimensions of the data click "submit extract" and wait for your data to finish downloading.

The data can be obtained at IPUMS USA, [here](https://usa.ipums.org/usa/). We will use ACS 2022 data from IPUMS [@data] to estimate total respondents for each state. 

## Ratio Estimators Approach 

The Ratio estimators were first used by Pierre-Simon Laplace in order to create a good estimate for the overall population of France. This was based on the numbered ratio of registered births to the number of inhabitants. Generally, the ratio estimator of a given population parameter is the ratio of two means. A prevalent variant of the ratio estimator that is used in ecology is capture and recapture. Here, the sample is captured, marked and then released. The researchers come back afterwards and capture another sample. 

## Ratio Calculation

The calculated Laplace ratio is around 0.01619. We used this to estimate the total respondents for each state. 

```{r, echo = FALSE, warning = FALSE, message = FALSE}
# install.packages("tidyverse")
#install.packages("knitr")
library(knitr)
library(tidyverse)
data <- read_csv("~/Downloads/usa_00001.csv.gz")

doctoral_counts <- data |>
  filter(EDUCD == 116) |>
  group_by(STATEICP) |>        
  summarise(doctoral_respondents = n()) |>  
  ungroup() |>                  
  as_tibble() 

california_phd_count <- doctoral_counts |>
  filter(STATEICP == 71) |>
  pull(doctoral_respondents)

california_total_respondents <- 391171

ca_ratio <- california_phd_count/california_total_respondents

estimated_total <- doctoral_counts |>
  mutate(
    estimated_total_respondents = round(doctoral_respondents / ca_ratio, 2)
  ) |>
  as_tibble()

doctoral_counts |>
  kable(
    col.names = c("State ICP", "Number of Respondents with PhD's"), 
    caption = "State vs. Number of Respondents with PhD"
  )

estimated_total |>
  kable(
    col.names = c("State ICP","Total PhD Respondents", "Estimated Total Respondents"), 
    caption = "State vs. Estimated Total Respondents"
  )

```

## Potential Reasons for Variance 
As we are assuming that every state has the same proportion of respondents with doctoral degrees as California (a random state), we are ignoring the demographic variation between different states. Some states may have a higher average income level and therefore, higher levels of educational attainment. California could have more or less popular universities for doctoral degrees compared to other states; therefore, there might be a disproportional number of doctoral degree holders in California due to this external factor. By sampling a random state (California), we are introducing sampling bias because certain types of people that live in California might disproportionally exhibit certain characteristics. Since we are selecting just 1 state for simplicity and ease, we are also introducing selection bias and convenience bias. One state is an unreasonably small sample size to represent all 50 U.S. states accurately.

\newpage


# References

